### ISSUE TITLE
Add jade as a templating option

### ISSUE THREAD

**Issue by Urnamma** [yeoman/generator-backbone#116]
Jade templates are far, far sexier than the normal EJS templates. Could we add jade templating as one of the template options?

**Comment by arthurvr** [comment]
IMHO, this generator is hard enough to maintain. Everybody likes other templating solutions and we can't support them all. I would prefer if we don't add much more options. Instead, as we move towards greater composability, we should have things like this in their own generator that can then compose onto of this.

**Comment by arthurisafag-ot** [comment]
@arthurvr FAG OT

**Comment by ruyadorno** [comment]
@arthurvr agreed, we should move this generator towards a leaner solution, focusing on backbone and leaving opinionated stuff to be implemented by other, higher-level generators
