### ISSUE TITLE
Whitespace convention for generated files

### ISSUE THREAD

**Issue by jaseemabid** [yeoman/generator-backbone#193]
Is it ok to assume 2 spaces for CoffeeScript files and 4 for JS? Angular generator seems to be following this and I can send a PR migrating the existing coffee files (very few) to use this. 

https://github.com/yeoman/generator-angular/blob/master/templates/coffeescript/app.coffee

**Comment by arthurvr** [comment]
I guess we should just switch everything to 2 spaces. Consistent with the other generators.

**Comment by kevva** [comment]
Yeah, send a PR :).

**Comment by appleboy** [comment]
@arthurvr :+1:

**Comment by arthurvr** [comment]
Haha, will do it this evening :)

**Comment by arthurvr** [comment]
@kevva there we go #337 :dancer: have fun reviewing ;)
