### ISSUE TITLE
404 with generated test files

### ISSUE THREAD

**Issue by fionnbharra** [yeoman/generator-backbone#228]
I'm using generator-backbone version 0.2.5  and Yo version 1.1.2.
I'm getting a 404 on my spec files. 

Steps to reproduce - 

Create a new app - yo backbone 
Generate a model using yo backbone:model User
Run tests - grunt test
Goto page http://localhost:9001/

    GET http://localhost:9001/test/models/question.js 404 (Not Found)

**Comment by ruyadorno** [comment]
@fionnbharra `grunt test` won't keep a server live for you, it'll just run the tests and exit right after

maybe you're interested in following #219
