### ISSUE TITLE
Custom Template for generated files from generator actions.

### ISSUE THREAD

**Issue by lesterzone** [yeoman/generator-backbone#264]
First: I didn't find anything related to override default templates.
Second: If there's an option to use our own templates I'll like to know about.

If no option available to override defaults templates, then...

Lets say user don't like model generated when I run:

~~~
yo backbone:model myModel
~~~

Template used for this command is:

~~~js
/*global <%= _.camelize(appname) %>, Backbone*/

<%= _.camelize(appname) %>.Models = <%= _.camelize(appname) %>.Models || {};

(function () {
    'use strict';

    <%= _.camelize(appname) %>.Models.<%= _.classify(name) %> = Backbone.Model.extend({

        url: '',

        initialize: function() {
        },

        defaults: {
        },

        validate: function(attrs, options) {
        },

        parse: function(response, options) {
            return response;
        }
    });

})();
~~~

So, what about an option to override that template? It will be helpful.
Here's my non elegant solution.
If the user wants to use his templates, add a new configuration under .yo-rc.js:

~~~js
{
  "generator-backbone": {
    "appPath": "app",
    ...
    "includeRequireJS": false,
    "templates": "customFolderHere"
  }
}

~~~

Then based on this templates config, copy and build the generated file.
User must create templates like: model.js, collection.js, view.js and view.ejs under customFolder in order to match generator requirements

Non elegant solution, but at least its an idea(not tested, yet) https://github.com/lesterzone/generator-backbone/commit/8732d341f8737e50a11d033fc0e545842fd03280

**Comment by ruyadorno** [comment]
This discussion is WAY out of scope of a humble generator, what you're guys were proposing back in the time of the original posts was a huge change in the Yeoman platform itself.

I'll close this issue for the sake of cleaning up our backlog for the **generator-backbone** repo, feel free to submit a new issue to https://github.com/yeoman/generator if you ever feel like interested on it again.
