### ISSUE TITLE
Yo backbone with jasmine and require.js

### ISSUE THREAD

**Issue by seyade** [yeoman/generator-backbone#276]
I love `yo backbone` but is it possible to set-up `jasmine` with `require.js` together in the next `yo backbone` version, so that we can test modules? And I find myself wasting a lot of time setting requirejs with jasmine together, and it's too much headache.

**Comment by ruyadorno** [comment]
Thanks everyone for the ideas. These days the Yeoman platform has a much bigger focus on composability and we'll be pushing back on adding new opinionated stuff like this in **generator-backbone** - our goal is to have a lean and focused base Backbone generator that other generators can build upon to deliver their own flavor.
