### ISSUE TITLE
Relative Glyphicons Path

### ISSUE THREAD

**Issue by reesejohn69** [yeoman/generator-backbone#281]
After building the app, I noticed it's using absolute path for Glyphicons. Is it possible to use the relative path for those icons once it's build?

Thanks.

**Comment by rjsteinert** [comment]
Why are relative paths a bad idea?

**Comment by rjsteinert** [comment]
@reesejohn69 In my `./app/styles/main.scss` I set `$icon-font-path: "../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";`.
