### ISSUE TITLE
generator does not create package.json or Gruntfile.js

### ISSUE THREAD

**Issue by jhendley25** [yeoman/generator-backbone#295]
The generator seems to fail to complete the scaffold.

I've updated Yo and generator-backbone, but ```yo backbone``` does not create a Gruntfile.js or package.json. No errors pop up when installing the generator or running it, so I'm kind of stymied here. I ran two other generators and those worked perfectly.

The resulting folder structure is:

- .editorconfig
- .gitattributes
- .gitignore
- .jshintrc
- .yo-rc.json
- app/
- bower.json
- test/

Mac OSX 10.9.5

Outpout after running ```yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js```
##### 

```
/Users/me/.rvm/gems/ruby-2.1.1/bin:/Users/me/.rvm/gems/ruby-2.1.1@global/bin:/Users/me/.rvm/rubies/ruby-2.1.1/bin:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/me/.rvm/bin
darwin { http_parser: '1.0',
  node: '0.10.32',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.28',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1i' }
cat: Gruntfile.js: No such file or directory
```

**Comment by arthurvr** [comment]
Can anyone of you test this using the latest version? Updating is possible using:

```
$ npm install --global generator-backbone
```

Sorry for getting back at y'all late.

**Comment by mipohja** [comment]
Version 0.3.5 works fine.
