### ISSUE TITLE
Generator creates usemin block for require which is no longer supported.

### ISSUE THREAD

**Issue by bmatto** [yeoman/generator-backbone#296]
Getting all set to build and ran "grunt", got this error 'Fatal error: require.js blocks are no more supported.'.  Found this ... https://github.com/yeoman/grunt-usemin/issues/112.  Are there plans to change the scaffold in regards to this incompatibility?

**Comment by wcainboundary** [comment]
+1 @omasback

**Comment by charneykaye** [comment]
I would not call this an effective workaround, y'all. Searching for an alternative https://github.com/yeoman/grunt-usemin/issues/112

**Comment by gpolyn** [comment]
Having same issue. Feels like generator-backbone is sidelined for now.
