### ISSUE TITLE
Bower install doesn't run on initial scaffold, even when output says "Running Bower install.."

### ISSUE THREAD

**Issue by qbunt** [yeoman/generator-backbone#298]
When scaffolding a new app, the output indicates "Running Bower install & npm install". Npm install runs just fine, but Bower install completely fails to run.

**Comment by SummitPatel** [comment]
Also having this issue. After manually running "bower install", most things load in except for the css file. I'm using Bootstrap with scss so I think the scss isn't being compiled into a css properly.

**Comment by arthurvr** [comment]
What version are y'all on? Would be great if anyone of you can try this using the master branch.

**Comment by tnarik** [comment]
Had the same issue with 0.3.5. Only the test bower components are installed.

**Comment by ruyadorno** [comment]
I can reproduce the issue on latest master
