### ISSUE TITLE
yo backbone:(something generator)

### ISSUE THREAD

**Issue by AbyChan** [yeoman/generator-backbone#318]
Sometimes generate this:
define([
    'jquery',
    'underscore',
    'backbone',
    'templates'
], function ($, _, Backbone, JST) {
    'use strict';
…………
……

and sometimes generate this:

App.Views = App.Views || {};

(function () {
    'use strict';

    App.Views.MainView = Backbone.View.extend({

What is the difference?
and how to import the latter object?

**Comment by arthurvr** [comment]
> What is the difference?

The latter is used when not using requirejs. 

> and how to import the latter object?

It's gets simply imported in the page by a script tag.

**Comment by arthurvr** [comment]
Is this issue okay to close? It's more like a question than a bug/request anyways.

**Comment by kevva** [comment]
Yup, thanks for keeping up with these old issues :D.
