### ISSUE TITLE
Templates generator-backbone/app/templates/ not used

### ISSUE THREAD

**Issue by gamaralf** [yeoman/generator-backbone#320]
There are some interesting files in `generator-backbone/app/templates` directory. How do I use them to generate an application? I have tried `yo backbone:app something` but I worked as if I simply typed `yo backbone`.

**Comment by arthurvr** [comment]
Those are the ones that are used when just using the generator like `yo backbone [app-name]`.

**Comment by arthurvr** [comment]
Can this issue be closed?
