### ISSUE TITLE
Not generating mocha tests

### ISSUE THREAD

**Issue by egpierro** [yeoman/generator-backbone#323]
The documentation and latest blog post of generator-backbone indicates that unit tests are automatically created with any of the components generated, but the generator is failing to do so. Is there any special setting or flag to enable this functionality?

**Comment by arthurvr** [comment]
Maybe you are just running into https://github.com/yeoman/generator-backbone/issues/252?

**Comment by egpierro** [comment]
Well that is just silly. Who would use BackboneJS without RequireJS?

**Comment by arthurvr** [comment]
That's totally right, but we already have an issue about that. Can somebody close this one?

**Comment by arthurvr** [comment]
Thanks
