### ISSUE TITLE
Node-Sass not compiling

### ISSUE THREAD

**Issue by BernhardBezdek** [yeoman/generator-backbone#324]
I'm not sure if this is the correct place to post an issue which concerns sass compilation.
I've just scaffolded a new backbone project and the installation worked fine node (0.12.0)

Then if I typed grunt serve, server was started as expected but the shown page doesn't have any styles.
After a lookup into ``.tmp`` folder, I saw there's no css folder present.
So changed main.css file manually and saw watcher detects the change but no css file is written.
````
>> File "app/styles/main.scss" changed.

Running "sass:server" (sass) task

Running "watch" task
Completed in 0.013s at Wed Mar 04 2015 14:17:50 GMT+0100 (CET) - Waiting...
````

Any suggestions to get the generator working again?

Thanks for any help

**Comment by Rawry** [comment]
Having similar issue. +1

**Comment by BernhardBezdek** [comment]
Issue is still present for me (after I made an npm update for all generators)
