### ISSUE TITLE
:hankey:

### ISSUE THREAD

**Issue by supergray** [yeoman/generator-backbone#328]
The maintain er of this repo has not been active on this repo as of past year. In my opinion unaccptable for an official google generator being. @sindresorhus @SBoudrias @kevva @addyosmani @eddiemonge

**Comment by supergray** [comment]
also the testing setup which is in many ways BROKEN isn't fixed after long long long

**Comment by SBoudrias** [comment]
Feel free to start sending PR and helping us maintaining this project.

**Comment by supergray** [comment]
You could have said that in a friendly way as well.

**Comment by SBoudrias** [comment]
I'm not sure I see what was unfriendly in my answer. We do need help maintaining our large number of projects.

**Comment by supergray** [comment]
> I'm not sure I see what was unfriendly in my answer. We do need help maintaining our large number of projects.

Your comment was extremely rude, that's what I meant.
