### ISSUE TITLE
Add support for ES6 using Babel 

### ISSUE THREAD

**Issue by thejameskyle** [yeoman/generator-backbone#341]
I can contibute a PR for this

**Comment by arthurvr** [comment]
:+1: on Babel (optionally).

I wonder what the view of the backbone community on coffeescript is these days but I kinda feel like we can get rid of it (similar to what we did in generator-webapp). What does the rest think?

**Comment by marian-r** [comment]
I think including Babel into this generator is more complex task than in generator-webapp (https://github.com/yeoman/generator-webapp/pull/543), as it involves making it work with RequireJS. I have it working for my own project, but I am not sure if the same configuration can cover all the edge cases here. And build with RequireJS is now working anyway (#299, #300).

+1 on removing CoffeeScript

**Comment by ruyadorno** [comment]
+1 to remove CoffeeScript altogether, this would be a HUGE maintenance win in the long term as it would reduce a lot the complexity of the codebase + get rid of 25% of all template files.
