### ISSUE TITLE
The grunt-sass in out-of-date

### ISSUE THREAD

**Issue by Boelroy** [yeoman/generator-backbone#343]
When I run npm install , it fails to build the grunt-sass. But when I change the version 0.17.0 to the latest version of the grunt-sass, and the npm works well. I think you may change the version of grunt-sass to the latest version.( I not sure the latest version of the grunt-sass works well the old version of node. My node version is 0.12.2 on Mac )

**Comment by rjsteinert** [comment]
Duplicate issue at #329
