### ISSUE TITLE
Build & serve issue

### ISSUE THREAD

**Issue by Bogdaan** [yeoman/generator-backbone#344]
When you in work process (serve runing) and you run 
***grunt build***
livereload and other runing tasks will crash ( because build.js run clean:tmp task )

**Comment by kevva** [comment]
Why are you running them simultaneously?

**Comment by Bogdaan** [comment]
I share result of my work over ssh+rsync to remote host (add rsync task to build task).

**Comment by mteodori** [comment]
I would stop the development server, build and sync the dist directory if it doesn't take too long
or use git to trigger the build and rsync somewhere else when there are changes, for example a CI server job like jenkins, even installed locally

**Comment by eddiemonge** [comment]
What ^^ said
