### ISSUE TITLE
Update `yeoman-generator` to latest

### ISSUE THREAD

**Issue by arthurvr** [yeoman/generator-backbone#346]
We need to update to the latest `yeoman-generator` version and fix all incompatibilities.

**Comment by mdxprograms** [comment]
+ 1

**Comment by mdxprograms** [comment]
yes please

**Comment by tconroy** [comment]
:+1:

**Comment by arthurvr** [comment]
Anyone looking here, PR welcome :)

**Comment by tconroy** [comment]
I'll see if I can pull something together after work.

**Comment by arthurvr** [comment]
Awesome!

**Comment by arthurvr** [comment]
Was you able to work on something @tconroy? :)

**Comment by tconroy** [comment]
Sorry, didn't get a chance to yet.

**Comment by ruyadorno** [comment]
I'll give this one a try, I have updated multiple generators before and I'm quite used to the new APIs.

**Comment by arthurvr** [comment]
Yay! Thanks @ruyadorno! :)

**Comment by tconroy** [comment]
Thanks @ruyadorno ! Apologies I couldn't get around to it, been busy with other work.
