### ISSUE TITLE
Call for a new maintainer

### ISSUE THREAD

**Issue by kevva** [yeoman/generator-backbone#349]
Since nobody is actively maintaining this anymore it needs a new maintainer. If anyone is interested that'd be very helpful! Otherwise we should deprecate this in favor of a community alternative or something.

**Comment by sindresorhus** [comment]
:+1:

**Comment by arthurvr** [comment]
Sure :+1:! It would be awesome to see someone picking this up!

**Comment by hemanth** [comment]
:+1:

**Comment by arthurvr** [comment]
Is there any way we can get the Backbone's community attention on this ticket? There should be people that are willing to pick it up, but maybe didn't catch this ticket.

**Comment by hemanth** [comment]
Did this get tweeted from the official yeoman account?

**Comment by arthurvr** [comment]
> Did this get tweeted from the official yeoman account?

Don't think so, but sounds like a good idea. Who has the power to do so?

**Comment by ruyadorno** [comment]
I'm up for the challenge :blush: feel free to go ahead and make the announcement if you want more people in though

**Comment by arthurvr** [comment]
That is super awesome, thanks Ruy!

Let's leave this one open for some time longer as having multiple people on
board would be even better :)

**Comment by ruyadorno** [comment]
:+1: :+1: :+1:

**Comment by haakonjack** [comment]
@ruyadorno just let me know there were maintainer positions available here :) I've been working with him to build some app-specific for Backbone/Marionette generators. would be happy to help if there's still room!

**Comment by arthurvr** [comment]
@haakonjack Of course there's still room, the more people the merrier :) Thanks!

**Comment by arthurvr** [comment]
@sindresorhus @addyosmani Can anyone add Ruy to this repo? He's done a neat PR and was up for maintaining this so why not :)

**Comment by sindresorhus** [comment]
@arthurvr Done.

**Comment by arthurvr** [comment]
I think I'm going to close this now. @ruyadorno has been doing awesome work, and we never got much more response on this issue so it doesn't make sense to keep this open.

**Comment by kevva** [comment]
:+1:
