### ISSUE TITLE
^^^ SyntaxError: Unexpected token ILLEGAL at exports.runInThisContext (vm.js:73:16)

### ISSUE THREAD

**Issue by joe-liquid** [yeoman/generator-backbone#351]
I am trying to run yo backbone to scaffold an app. After the initial "What more would you like?" prompt I see the following error:

/usr/local/lib/node_modules/generator-mocha/node_modules/yeoman-generator/node_modules/lodash/index.js:10619
    /**
    ^^^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-mocha/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

I am on node v0.12.6 and 2.11.2 for npm. Do you know what the issue is here. I am trying this with a regular node install. Not managed by homebrew.

**Comment by tconroy** [comment]
what do you get with `yo --version`?

**Comment by arthurvr** [comment]
More importantly, what version of generator-backbone are you on?

```
$ npm info generator-backbone | grep 'version:'
```

**Comment by joe-liquid** [comment]
version: '0.3.5',

**Comment by arthurvr** [comment]
And the yo version?

**Comment by joe-liquid** [comment]
I can get past the above stage now but it looks like there are issues with the sass:dist task. I will upload this as a separate issue so you can close this one.

**Comment by stephanebouget** [comment]
same error for me.
Fixed after compass re-install :

$ gem update --system
$ gem install compass

**Comment by stephanebouget** [comment]
same issue.
revert to 0.3.0 works for me :

$ npm install -g generator-backbone@0.3.0
$ yo backbone

**Comment by arthurvr** [comment]
@stephanebachelier Mind trying using the generator-backbone `master` branch and using the latest yo? Thanks.

**Comment by ruyadorno** [comment]
I expect this to have been solved with the migration to the new **yeoman/generator** API + no feedback so I'm closing it again.
