### ISSUE TITLE
Local Npm module "grunt-sass" not found. Is it installed?

### ISSUE THREAD

**Issue by joe-liquid** [yeoman/generator-backbone#352]
When I run the Grunt build task I get "Local Npm module "grunt-sass" not found. Is it installed?". It looks like the NPM module grunt-sass is not installing correctly.

**Comment by arthurvr** [comment]
Try if deleting the `node_modules` folder and `npm install` again fixes it. Likely it was just a one-off installation error.

Be sure that you're on the latest version of npm.

**Comment by joe-liquid** [comment]
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.

**Comment by joe-liquid** [comment]
That is the debug output when I run npm install.

**Comment by arthurvr** [comment]
What's your node version?

**Comment by joe-liquid** [comment]
Node version is v0.12.6
npm version is 2.11.2

Node and npm have been installed via the pkg installer on https://nodejs.org/.

**Comment by arthurvr** [comment]
The issues with grunt-sass were fixed in https://github.com/yeoman/generator-backbone/commit/267ad5d475e74ba0568a6b9a292f7aef72d205b2. That's not yet released yet, so you will need to bump grunt-sass yourself as seen in the commit.

@sindresorhus @kevva Time to do a new release for this generator?
