### ISSUE TITLE
Make a release with the latest fixes

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-backbone#357]

**Comment by arthurvr** [comment]
I don't use this generator, but if some people can help me confirm everything is still working fine on master I'm happy to pull out a release.

**Comment by ruyadorno** [comment]
@rjsteinert @k-funk I know you guys mentioned that you were running the generator from `master`, could you help us out with the test effort for the new release?

@arthurvr one thing I would suggest is that maybe this is a good timing for a `1.0.0` release - along with the entire yeoman API upgrade

One last thing, I'd like to see #359 and #368 merged in first :blush:

**Comment by k-funk** [comment]
@ruyadorno, unfortunately, my experience with unit testing in js, and node as a whole is very limited. :(

**Comment by rjsteinert** [comment]
@ruyadorno I'd be happy to help out with testing. Do we want to write tests or just tool around and manually test things? Who is officially maintainer right now?

**Comment by rjsteinert** [comment]
@ revathskumar Are you maintainer now? Per https://github.com/yeoman/generator-backbone/commit/775201a099122f73c234b3f54d9da9027a98afe9

**Comment by addyosmani** [comment]
#359 landed. Waiting on reviews for #368 before we move ahead.

**Comment by ruyadorno** [comment]
@rjsteinert I think that for now the only active maintainers are me and @arthurvr 

@k-funk I was thinking more of manual tests, I just want to have a couple of extra eyes testing the multiple workflow variations and validating that everything works as expected, nothing too complex

**Comment by ruyadorno** [comment]
ok, I think we should also wait for @marian-r's fixes, the RequireJS workflow is broken on master and it wouldn't be wise to make a release knowing that.

**Comment by ruyadorno** [comment]
@addyosmani #372 landed on `master` fixing most of the issues with the **requirejs** build - I would advise for a `v0.3.6` release now as we fixed MANY issues that are present on the latest release (also we are now using the latest yeoman API).

**Comment by ruyadorno** [comment]
@arthurvr could you publish a new patch release, please? :blush:

**Comment by ruyadorno** [comment]
@addyosmani :+1: done, I'll try to pull those with a better frequency now
