### ISSUE TITLE
app/index.html is missing after running yo backbone command

### ISSUE THREAD

**Issue by vganesh** [yeoman/generator-backbone#361]
After running the following command in an empty directory, I expect to see app/index.html and this file is missing. 

$ yo backbone test

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I include HTML5 Boilerplate, jQuery, Backbone.js and Modernizr.
? What more would you like? Twitter Bootstrap for Sass, Use RequireJs
   create test/bower.json
   create test/.bowerrc
   create .gitignore
   create test/spec/test.js
   create .gitattributes
   create test/index.html
   create .bowerrc

I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.

   create ../bower.json
   create ../.jshintrc
   create ../.editorconfig
   create Gruntfile.js
   create package.json
   create app/styles/main.scss
   create ../app/404.html
   create ../app/favicon.ico
   create ../app/robots.txt
   create app/index.html
   create app/scripts/main.js

I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

bower mocha#~1.14.0             cached git://github.com/mochajs/mocha.git#1.14.0
bower mocha#~1.14.0           validate 1.14.0 against git://github.com/mochajs/mocha.git#~1.14.0
...
/Users/vganesh/tmp/backbone
$ find . 
.
./.editorconfig
./.gitattributes
./.gitignore
./.jshintrc
./.yo-rc.json
./app
./app/404.html
./app/favicon.ico
./app/images
./app/robots.txt
./app/scripts
./app/scripts/vendor
./app/styles
./bower.json
./test
./test/.bowerrc
./test/app
./test/app/index.html
./test/app/scripts
./test/app/scripts/main.js
./test/app/styles
./test/app/styles/main.scss
./test/bower.json
./test/Gruntfile.js
./test/index.html
./test/package.json
./test/spec
./test/spec/test.js

**Comment by rjsteinert** [comment]
Things are a bit broken in this generator it seems. Are you using the latest code? I do ...

```
git clone git@github.com:yeoman/generator-backbone.git
cd generator-backbone
npm install
npm link
```

And then to update it later go to that folder you installed to and run `git pull`. Do you still see this error after that? Also, I've run into issues with earlier versions of node. I'm running v0.12.7 which seems to be working ok. There is however now nodejs v4.1.0 out which I haven't touched for fear of borking all the node projects I'm working on. I wonder if the maintainers of this generator are using that new version...

**Comment by ruyadorno** [comment]
I'm running the generator on `node@4.1.1` and can't reproduce it, @vganesh can you provide more information?

Especially try running from the `master` branch like @rjsteinert suggested, that would be very helpful :blush:

**Comment by vganesh** [comment]
Hello @rjsteinert,
I am getting 'Could not read from remote repository' error. Can you please let me know what I need to do to fix this error? Thx, 

/Users/vganesh/work/javascript/testBackbone
$ git clone git@github.com:yeoman/generator-backbone.git
Cloning into 'generator-backbone'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/Users/vganesh/work/javascript/testBackbone

**Comment by vganesh** [comment]
I am not able to reproduce this issue on my new macbook. Thanks for the help. This issue can be closed.

**Comment by vganesh** [comment]
This issue can be closed. I am not able to reproduce it any more. Thanks and regards,
