### ISSUE TITLE
Unable to use generator-backbone in windows 7

### ISSUE THREAD

**Issue by rkommine** [yeoman/generator-backbone#375]
Hi,

I have installed the following on windows 7:

> node -v
v4.2.3

> npm -v
3.5.2

> yo --version
1.5.0

Then I installed the generator-backbone & tried the following command.
yo backbone "app"

This is giving the following error:

npm WARN bower-requirejs@1.2.0 requires a peer of bower@^1.x but none was installed.
npm WARN grunt-bower-requirejs@1.1.1 requires a peer of bower@^1.x but none was installed.
npm WARN peppywalls@0.0.0 No description
npm WARN peppywalls@0.0.0 No repository field.
npm WARN peppywalls@0.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\\Bin\\nodejs\\node.exe" "D:\\userdata\\rkommine\\Application Data\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Bin\xampp\htdocs\Yeomen_Projects\project03\npm-debug.log
bower jquery#~2.1.0             ENOGIT git is not installed or not in the PATH

How to fix this error. I have attached the npm-debug.log
Could you please help to use the generator in windows.

Regards,
Ramakrishna
[npm-debug.txt](https://github.com/yeoman/generator-backbone/files/61356/npm-debug.txt)

**Comment by arthurvr** [comment]
Thanks for the report. Can you try using the latest generator-backbone version? Just update using `npm i -g generator-backbone` and try again.

**Comment by rkommine** [comment]
Hi,

Many thanks for the support. After updating the generator-backbone now I was not facing any issue.
Once again Thanks for your support.

Regards,
Ramakrishna
