### ISSUE TITLE
Not sure yet which one is getting the error grunt-require or grunt-usemin or else

### ISSUE THREAD

**Issue by elwebdeveloper** [yeoman/generator-backbone#376]
After running yo backbone app, I get the following error when running grunt or grunt build

>>Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin

>>Running "requirejs:dist" (requirejs) task
Error: Error: Missing either an "out" or "dir" config value. If using "appDir" for a full project optimization, use "dir". If you want to optimize to one file, use "out".
>>     at Function.build.createConfig (/Users/edison/Sites/backbone-generated/node_modules/grunt-requirejs/node_modules/requirejs/bin/r.js:31109:19)
Warning: Task "requirejs:dist" failed. Use --force to continue.

>>Aborted due to warnings.

**Comment by lauradaniela** [comment]
@elwebdeveloper you can resolve the error?

**Comment by marian-r** [comment]
@elwebdeveloper do you use the latest version of the generator? If yes and still getting the error, could you please specify what options are used when generating the project?

**Comment by elwebdeveloper** [comment]
I think it has been resolve, after last re-install all previous problem seen to be gone. I just ran grunt build after creating a /model/collection/route/view/views again

**Comment by marian-r** [comment]
Thank you @elwebdeveloper. Please close the issue.

**Comment by ruyadorno** [comment]
:+1: thanks for the help @marian-r
