### ISSUE TITLE
404 main css, main.js

### ISSUE THREAD

**Issue by sun-ks** [yeoman/generator-backbone#378]
Hello people. I installed Backbone.js generator <code>yo backbone my-app</code> After i generated view <code>backbone:view blog</code>. Then i run <code>grunt server</code> and i see my app in http://localhost:9000/ cool! =) But if i will write in my view - 'blog' anything. For example write - <code> console.log('init my view');</code> in initialize: method my view.  I have errors - 
<code>
Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:4 Uncaught ReferenceError: Invalid left-hand side in assignment
http://localhost:9000/scripts/templates.js Failed to load resource: the server responded with a status of 404 (Not Found)
video.js:3 Uncaught ReferenceError: VodBackboneGenerator is not defined
http://localhost:9000/styles/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
</code>

If stop <code>grunt server</code> and run again, the errors will not be.

Screen photo - http://screencast.com/t/huSQwcRP
Screen video - http://screencast.com/t/yzWi7FNj

**Comment by tekgrunt** [comment]
Did you ever make an headway with this? It seems I am experiencing the same issue.

**Comment by mteodori** [comment]
looks like it happens when the directory you generate in or the application name provided on the command line contains a dash, then the app namespace is generated via param-case rather than pascal-case in scripts/main.js while the one in the subgenerators is correct
