### ISSUE TITLE
jasmine can't find es5 shim

### ISSUE THREAD

**Issue by bkempner** [yeoman/generator-backbone#387]
If I generate my project with jasmine, I get the following error when running the jasmine task:

```
grunt jasmine
Running "jasmine:all" (jasmine) task
Warning: Unable to read "/myproject/node_modules/grunt-contrib-jasmine/tasks/lib/../../node_modules/es5-shim/es5-shim.js" file (Error code: ENOENT). Use --force to continue.
```

Seems to be related to this issue: https://github.com/gruntjs/grunt-contrib-jasmine/issues/193

As suggested, bumping `grunt-jasmine-contrib` version to `0.9.2` fixed the issue for me.

**Comment by AashishMaheshwari** [comment]
RESOLVED: 
1.mention 0.9.2 version for grunt-jasmine-contrib in package.json
2. delete 'grunt-jasmine-contrib' folder from node_modules
3. run npm install ,It will install new version of 'grunt-jasmine-contrib' which will resolve the issue.

**Comment by bkempner** [comment]
Thanks @mteodori !

**Comment by alexch** [comment]
`grunt-contrib-jasmine` not `grunt-jasmine-contrib`
